package parsing;

import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;

//import java.text.ParseException;
import org.json.simple.JSONObject;
import org.json.simple.JSONValue;
import org.json.simple.parser.ParseException;

public class ParseJsonToJsonObj implements Parse{
	
	// parsing da un file
	public JSONObject fromFile(String nomeFIle)
	{
		return null;
	}
	
	// parsing direttamanete dalla connesione
	public JSONObject fromHttp(/*HttpURLConnection connesione*/)
	{
		try {
			
			//InputStream in = connesione.getInputStream();
			
			 String contenuto = "";
			 String riga = "";
			 try {
			   //InputStreamReader inR = new InputStreamReader( in );
			   //BufferedReader buf = new BufferedReader( inR );
			  
			  // while ( ( riga = buf.readLine() ) != null ) {
				   //contenuto = riga + contenuto;
			   //}
			 } finally {
				  // in.close();
			 }
			System.out.println( contenuto + "sono qui");
			JSONObject jasonObj = (JSONObject) JSONValue.parseWithException("{\r\n"
					+ "    \"statuses\": [\r\n"
					+ "        {\r\n"
					+ "            \"metadata\": {\r\n"
					+ "                \"result_type\": \"popular\",\r\n"
					+ "                \"iso_language_code\": \"it\"\r\n"
					+ "            },\r\n"
					+ "            \"in_reply_to_status_id_str\": null,\r\n"
					+ "            \"in_reply_to_status_id\": null,\r\n"
					+ "            \"coordinates\": null,\r\n"
					+ "            \"created_at\": \"Sun Jan 09 18:49:07 +0000 2022\",\r\n"
					+ "            \"truncated\": true,\r\n"
					+ "            \"in_reply_to_user_id_str\": null,\r\n"
					+ "            \"source\": \"<a href=\\\"http://twitter.com/download/iphone\\\" rel=\\\"nofollow\\\">Twitter for iPhone</a>\",\r\n"
					+ "            \"retweet_count\": 487,\r\n"
					+ "            \"retweeted\": false,\r\n"
					+ "            \"geo\": null,\r\n"
					+ "            \"in_reply_to_screen_name\": null,\r\n"
					+ "            \"is_quote_status\": false,\r\n"
					+ "            \"id_str\": \"1480250297889009665\",\r\n"
					+ "            \"in_reply_to_user_id\": null,\r\n"
					+ "            \"favorite_count\": 817,\r\n"
					+ "            \"id\": 1480250297889009665,\r\n"
					+ "            \"text\": \"Malgrado l’immancabile aiuto sul rigoretto, stavolta i gobbi se la prendono nder posto. Fa sempre piacere, a tutti… https://t.co/cwjavDY2fT\",\r\n"
					+ "            \"place\": null,\r\n"
					+ "            \"contributors\": null,\r\n"
					+ "            \"lang\": \"it\",\r\n"
					+ "            \"user\": {\r\n"
					+ "                \"utc_offset\": null,\r\n"
					+ "                \"friends_count\": 334,\r\n"
					+ "                \"profile_image_url_https\": \"https://pbs.twimg.com/profile_images/1350824187313709063/Lk3AyUWk_normal.jpg\",\r\n"
					+ "                \"listed_count\": 1695,\r\n"
					+ "                \"profile_background_image_url\": \"http://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"default_profile_image\": false,\r\n"
					+ "                \"favourites_count\": 83,\r\n"
					+ "                \"description\": \"pronto alla battaglia. Giornalista. Cuori rossoblù. Tetris, Matrix, inonda, giornale radio @tpi\",\r\n"
					+ "                \"created_at\": \"Wed Dec 30 22:20:17 +0000 2009\",\r\n"
					+ "                \"is_translator\": false,\r\n"
					+ "                \"withheld_in_countries\": [],\r\n"
					+ "                \"profile_background_image_url_https\": \"https://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"protected\": false,\r\n"
					+ "                \"screen_name\": \"lucatelese\",\r\n"
					+ "                \"id_str\": \"100610543\",\r\n"
					+ "                \"profile_link_color\": \"1DA1F2\",\r\n"
					+ "                \"is_translation_enabled\": false,\r\n"
					+ "                \"translator_type\": \"none\",\r\n"
					+ "                \"id\": 100610543,\r\n"
					+ "                \"geo_enabled\": false,\r\n"
					+ "                \"profile_background_color\": \"C0DEED\",\r\n"
					+ "                \"lang\": null,\r\n"
					+ "                \"has_extended_profile\": true,\r\n"
					+ "                \"profile_sidebar_border_color\": \"C0DEED\",\r\n"
					+ "                \"profile_text_color\": \"333333\",\r\n"
					+ "                \"verified\": true,\r\n"
					+ "                \"profile_image_url\": \"http://pbs.twimg.com/profile_images/1350824187313709063/Lk3AyUWk_normal.jpg\",\r\n"
					+ "                \"time_zone\": null,\r\n"
					+ "                \"url\": \"https://t.co/fFkmosQ8Pe\",\r\n"
					+ "                \"contributors_enabled\": false,\r\n"
					+ "                \"profile_background_tile\": false,\r\n"
					+ "                \"profile_banner_url\": \"https://pbs.twimg.com/profile_banners/100610543/1504297282\",\r\n"
					+ "                \"entities\": {\r\n"
					+ "                    \"description\": {\r\n"
					+ "                        \"urls\": []\r\n"
					+ "                    },\r\n"
					+ "                    \"url\": {\r\n"
					+ "                        \"urls\": [\r\n"
					+ "                            {\r\n"
					+ "                                \"display_url\": \"lucatelese.it\",\r\n"
					+ "                                \"indices\": [\r\n"
					+ "                                    0,\r\n"
					+ "                                    23\r\n"
					+ "                                ],\r\n"
					+ "                                \"expanded_url\": \"http://www.lucatelese.it\",\r\n"
					+ "                                \"url\": \"https://t.co/fFkmosQ8Pe\"\r\n"
					+ "                            }\r\n"
					+ "                        ]\r\n"
					+ "                    }\r\n"
					+ "                },\r\n"
					+ "                \"statuses_count\": 56296,\r\n"
					+ "                \"follow_request_sent\": null,\r\n"
					+ "                \"followers_count\": 344622,\r\n"
					+ "                \"profile_use_background_image\": true,\r\n"
					+ "                \"default_profile\": true,\r\n"
					+ "                \"following\": null,\r\n"
					+ "                \"name\": \"Luca Telese\",\r\n"
					+ "                \"location\": \"Roma\",\r\n"
					+ "                \"profile_sidebar_fill_color\": \"DDEEF6\",\r\n"
					+ "                \"notifications\": null\r\n"
					+ "            },\r\n"
					+ "            \"favorited\": false\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "            \"metadata\": {\r\n"
					+ "                \"result_type\": \"popular\",\r\n"
					+ "                \"iso_language_code\": \"in\"\r\n"
					+ "            },\r\n"
					+ "            \"in_reply_to_status_id_str\": null,\r\n"
					+ "            \"in_reply_to_status_id\": null,\r\n"
					+ "            \"possibly_sensitive\": false,\r\n"
					+ "            \"coordinates\": null,\r\n"
					+ "            \"created_at\": \"Mon Jan 10 05:38:38 +0000 2022\",\r\n"
					+ "            \"truncated\": true,\r\n"
					+ "            \"in_reply_to_user_id_str\": null,\r\n"
					+ "            \"source\": \"<a href=\\\"https://mobile.twitter.com\\\" rel=\\\"nofollow\\\">Twitter Web App</a>\",\r\n"
					+ "            \"retweet_count\": 231,\r\n"
					+ "            \"retweeted\": false,\r\n"
					+ "            \"geo\": null,\r\n"
					+ "            \"in_reply_to_screen_name\": null,\r\n"
					+ "            \"is_quote_status\": false,\r\n"
					+ "            \"id_str\": \"1480413754051284994\",\r\n"
					+ "            \"in_reply_to_user_id\": null,\r\n"
					+ "            \"favorite_count\": 837,\r\n"
					+ "            \"id\": 1480413754051284994,\r\n"
					+ "            \"text\": \"Sekitar tiga tahun lalu, Shalika Aurelia berjanji akan memberikan kejutan.\\n\\nJanjinya boleh jadi terlunasi; Shalika… https://t.co/3JgOj6e6CA\",\r\n"
					+ "            \"place\": null,\r\n"
					+ "            \"contributors\": null,\r\n"
					+ "            \"lang\": \"in\",\r\n"
					+ "            \"user\": {\r\n"
					+ "                \"utc_offset\": null,\r\n"
					+ "                \"friends_count\": 288,\r\n"
					+ "                \"profile_image_url_https\": \"https://pbs.twimg.com/profile_images/1066697250292678661/-ZsQ3C3e_normal.jpg\",\r\n"
					+ "                \"listed_count\": 864,\r\n"
					+ "                \"profile_background_image_url\": \"http://abs.twimg.com/images/themes/theme14/bg.gif\",\r\n"
					+ "                \"default_profile_image\": false,\r\n"
					+ "                \"favourites_count\": 1484,\r\n"
					+ "                \"description\": \"Berita, cerita, sejarah, taktik, dan analisis sepakbola | redaksi@panditfootball.com | Kirim tulisan https://t.co/DpnW5cfZzj |  https://t.co/pB0ggUqzUO\",\r\n"
					+ "                \"created_at\": \"Wed Nov 14 07:45:11 +0000 2012\",\r\n"
					+ "                \"is_translator\": false,\r\n"
					+ "                \"withheld_in_countries\": [],\r\n"
					+ "                \"profile_background_image_url_https\": \"https://abs.twimg.com/images/themes/theme14/bg.gif\",\r\n"
					+ "                \"protected\": false,\r\n"
					+ "                \"screen_name\": \"panditfootball\",\r\n"
					+ "                \"id_str\": \"947281567\",\r\n"
					+ "                \"profile_link_color\": \"E81C4F\",\r\n"
					+ "                \"is_translation_enabled\": false,\r\n"
					+ "                \"translator_type\": \"regular\",\r\n"
					+ "                \"id\": 947281567,\r\n"
					+ "                \"geo_enabled\": true,\r\n"
					+ "                \"profile_background_color\": \"000000\",\r\n"
					+ "                \"lang\": null,\r\n"
					+ "                \"has_extended_profile\": false,\r\n"
					+ "                \"profile_sidebar_border_color\": \"000000\",\r\n"
					+ "                \"profile_text_color\": \"000000\",\r\n"
					+ "                \"verified\": true,\r\n"
					+ "                \"profile_image_url\": \"http://pbs.twimg.com/profile_images/1066697250292678661/-ZsQ3C3e_normal.jpg\",\r\n"
					+ "                \"time_zone\": null,\r\n"
					+ "                \"url\": \"https://t.co/907SsmymiS\",\r\n"
					+ "                \"contributors_enabled\": false,\r\n"
					+ "                \"profile_background_tile\": false,\r\n"
					+ "                \"profile_banner_url\": \"https://pbs.twimg.com/profile_banners/947281567/1628852822\",\r\n"
					+ "                \"entities\": {\r\n"
					+ "                    \"description\": {\r\n"
					+ "                        \"urls\": [\r\n"
					+ "                            {\r\n"
					+ "                                \"display_url\": \"bit.ly/sharingpandit\",\r\n"
					+ "                                \"indices\": [\r\n"
					+ "                                    101,\r\n"
					+ "                                    124\r\n"
					+ "                                ],\r\n"
					+ "                                \"expanded_url\": \"http://bit.ly/sharingpandit\",\r\n"
					+ "                                \"url\": \"https://t.co/DpnW5cfZzj\"\r\n"
					+ "                            },\r\n"
					+ "                            {\r\n"
					+ "                                \"display_url\": \"fb.com/panditfootball\",\r\n"
					+ "                                \"indices\": [\r\n"
					+ "                                    128,\r\n"
					+ "                                    151\r\n"
					+ "                                ],\r\n"
					+ "                                \"expanded_url\": \"http://fb.com/panditfootball\",\r\n"
					+ "                                \"url\": \"https://t.co/pB0ggUqzUO\"\r\n"
					+ "                            }\r\n"
					+ "                        ]\r\n"
					+ "                    },\r\n"
					+ "                    \"url\": {\r\n"
					+ "                        \"urls\": [\r\n"
					+ "                            {\r\n"
					+ "                                \"display_url\": \"panditfootball.com\",\r\n"
					+ "                                \"indices\": [\r\n"
					+ "                                    0,\r\n"
					+ "                                    23\r\n"
					+ "                                ],\r\n"
					+ "                                \"expanded_url\": \"http://panditfootball.com\",\r\n"
					+ "                                \"url\": \"https://t.co/907SsmymiS\"\r\n"
					+ "                            }\r\n"
					+ "                        ]\r\n"
					+ "                    }\r\n"
					+ "                },\r\n"
					+ "                \"statuses_count\": 125082,\r\n"
					+ "                \"follow_request_sent\": null,\r\n"
					+ "                \"followers_count\": 539126,\r\n"
					+ "                \"profile_use_background_image\": false,\r\n"
					+ "                \"default_profile\": false,\r\n"
					+ "                \"following\": null,\r\n"
					+ "                \"name\": \"PanditFootball.com\",\r\n"
					+ "                \"location\": \"Indonesia\",\r\n"
					+ "                \"profile_sidebar_fill_color\": \"000000\",\r\n"
					+ "                \"notifications\": null\r\n"
					+ "            },\r\n"
					+ "            \"favorited\": false\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "            \"metadata\": {\r\n"
					+ "                \"result_type\": \"popular\",\r\n"
					+ "                \"iso_language_code\": \"it\"\r\n"
					+ "            },\r\n"
					+ "            \"in_reply_to_status_id_str\": null,\r\n"
					+ "            \"in_reply_to_status_id\": null,\r\n"
					+ "            \"possibly_sensitive\": false,\r\n"
					+ "            \"coordinates\": null,\r\n"
					+ "            \"created_at\": \"Sun Jan 09 13:41:43 +0000 2022\",\r\n"
					+ "            \"truncated\": true,\r\n"
					+ "            \"in_reply_to_user_id_str\": null,\r\n"
					+ "            \"source\": \"<a href=\\\"http://twitter.com/download/iphone\\\" rel=\\\"nofollow\\\">Twitter for iPhone</a>\",\r\n"
					+ "            \"retweet_count\": 567,\r\n"
					+ "            \"retweeted\": false,\r\n"
					+ "            \"geo\": null,\r\n"
					+ "            \"in_reply_to_screen_name\": null,\r\n"
					+ "            \"is_quote_status\": false,\r\n"
					+ "            \"id_str\": \"1480172939353985028\",\r\n"
					+ "            \"in_reply_to_user_id\": null,\r\n"
					+ "            \"favorite_count\": 3191,\r\n"
					+ "            \"id\": 1480172939353985028,\r\n"
					+ "            \"text\": \"In Venezia-Milan, due  gravi errori di Irrati  \\n1. la mancata espulsione di Saelemaekers dopo il fallo su Busio (5’… https://t.co/gPFg4va1t1\",\r\n"
					+ "            \"place\": null,\r\n"
					+ "            \"contributors\": null,\r\n"
					+ "            \"lang\": \"it\",\r\n"
					+ "            \"user\": {\r\n"
					+ "                \"utc_offset\": null,\r\n"
					+ "                \"friends_count\": 631,\r\n"
					+ "                \"profile_image_url_https\": \"https://pbs.twimg.com/profile_images/1251122322783842306/tkmrwCo4_normal.jpg\",\r\n"
					+ "                \"listed_count\": 437,\r\n"
					+ "                \"profile_background_image_url\": \"http://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"default_profile_image\": false,\r\n"
					+ "                \"favourites_count\": 32952,\r\n"
					+ "                \"description\": \"Giornalista. Da 40 anni seguo il Calcio: era il mio sogno,è diventato il mio lavoro e la mia vita. https://t.co/rwh0TG6vuR\",\r\n"
					+ "                \"created_at\": \"Sat Sep 06 13:07:47 +0000 2014\",\r\n"
					+ "                \"is_translator\": false,\r\n"
					+ "                \"withheld_in_countries\": [],\r\n"
					+ "                \"profile_background_image_url_https\": \"https://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"protected\": false,\r\n"
					+ "                \"screen_name\": \"pisto_gol\",\r\n"
					+ "                \"id_str\": \"2762840061\",\r\n"
					+ "                \"profile_link_color\": \"1DA1F2\",\r\n"
					+ "                \"is_translation_enabled\": false,\r\n"
					+ "                \"translator_type\": \"none\",\r\n"
					+ "                \"id\": 2762840061,\r\n"
					+ "                \"geo_enabled\": true,\r\n"
					+ "                \"profile_background_color\": \"C0DEED\",\r\n"
					+ "                \"lang\": null,\r\n"
					+ "                \"has_extended_profile\": true,\r\n"
					+ "                \"profile_sidebar_border_color\": \"C0DEED\",\r\n"
					+ "                \"profile_text_color\": \"333333\",\r\n"
					+ "                \"verified\": true,\r\n"
					+ "                \"profile_image_url\": \"http://pbs.twimg.com/profile_images/1251122322783842306/tkmrwCo4_normal.jpg\",\r\n"
					+ "                \"time_zone\": null,\r\n"
					+ "                \"url\": null,\r\n"
					+ "                \"contributors_enabled\": false,\r\n"
					+ "                \"profile_background_tile\": false,\r\n"
					+ "                \"profile_banner_url\": \"https://pbs.twimg.com/profile_banners/2762840061/1580489218\",\r\n"
					+ "                \"entities\": {\r\n"
					+ "                    \"description\": {\r\n"
					+ "                        \"urls\": [\r\n"
					+ "                            {\r\n"
					+ "                                \"display_url\": \"instagram.com/pisto_gol/?hl=…\",\r\n"
					+ "                                \"indices\": [\r\n"
					+ "                                    99,\r\n"
					+ "                                    122\r\n"
					+ "                                ],\r\n"
					+ "                                \"expanded_url\": \"https://www.instagram.com/pisto_gol/?hl=it\",\r\n"
					+ "                                \"url\": \"https://t.co/rwh0TG6vuR\"\r\n"
					+ "                            }\r\n"
					+ "                        ]\r\n"
					+ "                    }\r\n"
					+ "                },\r\n"
					+ "                \"statuses_count\": 80247,\r\n"
					+ "                \"follow_request_sent\": null,\r\n"
					+ "                \"followers_count\": 162447,\r\n"
					+ "                \"profile_use_background_image\": true,\r\n"
					+ "                \"default_profile\": true,\r\n"
					+ "                \"following\": null,\r\n"
					+ "                \"name\": \"Maurizio Pistocchi\",\r\n"
					+ "                \"location\": \"Italia\",\r\n"
					+ "                \"profile_sidebar_fill_color\": \"DDEEF6\",\r\n"
					+ "                \"notifications\": null\r\n"
					+ "            },\r\n"
					+ "            \"favorited\": false\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "            \"metadata\": {\r\n"
					+ "                \"result_type\": \"popular\",\r\n"
					+ "                \"iso_language_code\": \"it\"\r\n"
					+ "            },\r\n"
					+ "            \"quoted_status\": {\r\n"
					+ "                \"metadata\": {\r\n"
					+ "                    \"result_type\": \"popular\",\r\n"
					+ "                    \"iso_language_code\": \"it\"\r\n"
					+ "                },\r\n"
					+ "                \"in_reply_to_status_id_str\": null,\r\n"
					+ "                \"in_reply_to_status_id\": null,\r\n"
					+ "                \"coordinates\": null,\r\n"
					+ "                \"created_at\": \"Sun Jan 09 18:49:07 +0000 2022\",\r\n"
					+ "                \"truncated\": true,\r\n"
					+ "                \"in_reply_to_user_id_str\": null,\r\n"
					+ "                \"source\": \"<a href=\\\"http://twitter.com/download/iphone\\\" rel=\\\"nofollow\\\">Twitter for iPhone</a>\",\r\n"
					+ "                \"retweet_count\": 487,\r\n"
					+ "                \"retweeted\": false,\r\n"
					+ "                \"geo\": null,\r\n"
					+ "                \"in_reply_to_screen_name\": null,\r\n"
					+ "                \"is_quote_status\": false,\r\n"
					+ "                \"id_str\": \"1480250297889009665\",\r\n"
					+ "                \"in_reply_to_user_id\": null,\r\n"
					+ "                \"favorite_count\": 817,\r\n"
					+ "                \"id\": 1480250297889009665,\r\n"
					+ "                \"text\": \"Malgrado l’immancabile aiuto sul rigoretto, stavolta i gobbi se la prendono nder posto. Fa sempre piacere, a tutti… https://t.co/cwjavDY2fT\",\r\n"
					+ "                \"place\": null,\r\n"
					+ "                \"contributors\": null,\r\n"
					+ "                \"lang\": \"it\",\r\n"
					+ "                \"user\": {\r\n"
					+ "                    \"utc_offset\": null,\r\n"
					+ "                    \"friends_count\": 334,\r\n"
					+ "                    \"profile_image_url_https\": \"https://pbs.twimg.com/profile_images/1350824187313709063/Lk3AyUWk_normal.jpg\",\r\n"
					+ "                    \"listed_count\": 1695,\r\n"
					+ "                    \"profile_background_image_url\": \"http://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                    \"default_profile_image\": false,\r\n"
					+ "                    \"favourites_count\": 83,\r\n"
					+ "                    \"description\": \"pronto alla battaglia. Giornalista. Cuori rossoblù. Tetris, Matrix, inonda, giornale radio @tpi\",\r\n"
					+ "                    \"created_at\": \"Wed Dec 30 22:20:17 +0000 2009\",\r\n"
					+ "                    \"is_translator\": false,\r\n"
					+ "                    \"withheld_in_countries\": [],\r\n"
					+ "                    \"profile_background_image_url_https\": \"https://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                    \"protected\": false,\r\n"
					+ "                    \"screen_name\": \"lucatelese\",\r\n"
					+ "                    \"id_str\": \"100610543\",\r\n"
					+ "                    \"profile_link_color\": \"1DA1F2\",\r\n"
					+ "                    \"is_translation_enabled\": false,\r\n"
					+ "                    \"translator_type\": \"none\",\r\n"
					+ "                    \"id\": 100610543,\r\n"
					+ "                    \"geo_enabled\": false,\r\n"
					+ "                    \"profile_background_color\": \"C0DEED\",\r\n"
					+ "                    \"lang\": null,\r\n"
					+ "                    \"has_extended_profile\": true,\r\n"
					+ "                    \"profile_sidebar_border_color\": \"C0DEED\",\r\n"
					+ "                    \"profile_text_color\": \"333333\",\r\n"
					+ "                    \"verified\": true,\r\n"
					+ "                    \"profile_image_url\": \"http://pbs.twimg.com/profile_images/1350824187313709063/Lk3AyUWk_normal.jpg\",\r\n"
					+ "                    \"time_zone\": null,\r\n"
					+ "                    \"url\": \"https://t.co/fFkmosQ8Pe\",\r\n"
					+ "                    \"contributors_enabled\": false,\r\n"
					+ "                    \"profile_background_tile\": false,\r\n"
					+ "                    \"profile_banner_url\": \"https://pbs.twimg.com/profile_banners/100610543/1504297282\",\r\n"
					+ "                    \"entities\": {\r\n"
					+ "                        \"description\": {\r\n"
					+ "                            \"urls\": []\r\n"
					+ "                        },\r\n"
					+ "                        \"url\": {\r\n"
					+ "                            \"urls\": [\r\n"
					+ "                                {\r\n"
					+ "                                    \"display_url\": \"lucatelese.it\",\r\n"
					+ "                                    \"indices\": [\r\n"
					+ "                                        0,\r\n"
					+ "                                        23\r\n"
					+ "                                    ],\r\n"
					+ "                                    \"expanded_url\": \"http://www.lucatelese.it\",\r\n"
					+ "                                    \"url\": \"https://t.co/fFkmosQ8Pe\"\r\n"
					+ "                                }\r\n"
					+ "                            ]\r\n"
					+ "                        }\r\n"
					+ "                    },\r\n"
					+ "                    \"statuses_count\": 56296,\r\n"
					+ "                    \"follow_request_sent\": null,\r\n"
					+ "                    \"followers_count\": 344622,\r\n"
					+ "                    \"profile_use_background_image\": true,\r\n"
					+ "                    \"default_profile\": true,\r\n"
					+ "                    \"following\": null,\r\n"
					+ "                    \"name\": \"Luca Telese\",\r\n"
					+ "                    \"location\": \"Roma\",\r\n"
					+ "                    \"profile_sidebar_fill_color\": \"DDEEF6\",\r\n"
					+ "                    \"notifications\": null\r\n"
					+ "                },\r\n"
					+ "                \"favorited\": false\r\n"
					+ "            },\r\n"
					+ "            \"in_reply_to_status_id_str\": null,\r\n"
					+ "            \"in_reply_to_status_id\": null,\r\n"
					+ "            \"created_at\": \"Sun Jan 09 19:44:24 +0000 2022\",\r\n"
					+ "            \"in_reply_to_user_id_str\": null,\r\n"
					+ "            \"source\": \"<a href=\\\"http://twitter.com/download/iphone\\\" rel=\\\"nofollow\\\">Twitter for iPhone</a>\",\r\n"
					+ "            \"quoted_status_id\": 1480250297889009665,\r\n"
					+ "            \"retweet_count\": 65,\r\n"
					+ "            \"retweeted\": false,\r\n"
					+ "            \"geo\": null,\r\n"
					+ "            \"in_reply_to_screen_name\": null,\r\n"
					+ "            \"is_quote_status\": true,\r\n"
					+ "            \"id_str\": \"1480264212903608321\",\r\n"
					+ "            \"in_reply_to_user_id\": null,\r\n"
					+ "            \"favorite_count\": 500,\r\n"
					+ "            \"id\": 1480264212903608321,\r\n"
					+ "            \"text\": \"È sempre il migliore. Nel calcio, come in politica. #finoallafine #[omissis] https://t.co/2dD7LKTFbg\",\r\n"
					+ "            \"place\": null,\r\n"
					+ "            \"lang\": \"it\",\r\n"
					+ "            \"favorited\": false,\r\n"
					+ "            \"possibly_sensitive\": false,\r\n"
					+ "            \"coordinates\": null,\r\n"
					+ "            \"truncated\": false,\r\n"
					+ "            \"quoted_status_id_str\": \"1480250297889009665\",\r\n"
					+ "            \"contributors\": null,\r\n"
					+ "            \"user\": {\r\n"
					+ "                \"utc_offset\": null,\r\n"
					+ "                \"friends_count\": 200,\r\n"
					+ "                \"profile_image_url_https\": \"https://pbs.twimg.com/profile_images/1050250422294929409/H-NqhQml_normal.jpg\",\r\n"
					+ "                \"listed_count\": 338,\r\n"
					+ "                \"profile_background_image_url\": \"http://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"default_profile_image\": false,\r\n"
					+ "                \"favourites_count\": 2112,\r\n"
					+ "                \"description\": \"Presidente della Commissione Finanze della Camera. Professore Associato di Economia all’Universita di Bologna. Qui (https://t.co/z5RPHrC0h2)trovate tutto su di me.\",\r\n"
					+ "                \"created_at\": \"Sun Jun 24 07:40:31 +0000 2012\",\r\n"
					+ "                \"is_translator\": false,\r\n"
					+ "                \"withheld_in_countries\": [],\r\n"
					+ "                \"profile_background_image_url_https\": \"https://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"protected\": false,\r\n"
					+ "                \"screen_name\": \"marattin\",\r\n"
					+ "                \"id_str\": \"616886078\",\r\n"
					+ "                \"profile_link_color\": \"1DA1F2\",\r\n"
					+ "                \"is_translation_enabled\": false,\r\n"
					+ "                \"translator_type\": \"none\",\r\n"
					+ "                \"id\": 616886078,\r\n"
					+ "                \"geo_enabled\": false,\r\n"
					+ "                \"profile_background_color\": \"C0DEED\",\r\n"
					+ "                \"lang\": null,\r\n"
					+ "                \"has_extended_profile\": true,\r\n"
					+ "                \"profile_sidebar_border_color\": \"C0DEED\",\r\n"
					+ "                \"profile_text_color\": \"333333\",\r\n"
					+ "                \"verified\": true,\r\n"
					+ "                \"profile_image_url\": \"http://pbs.twimg.com/profile_images/1050250422294929409/H-NqhQml_normal.jpg\",\r\n"
					+ "                \"time_zone\": null,\r\n"
					+ "                \"url\": \"https://t.co/z5RPHrC0h2\",\r\n"
					+ "                \"contributors_enabled\": false,\r\n"
					+ "                \"profile_background_tile\": false,\r\n"
					+ "                \"profile_banner_url\": \"https://pbs.twimg.com/profile_banners/616886078/1439963948\",\r\n"
					+ "                \"entities\": {\r\n"
					+ "                    \"description\": {\r\n"
					+ "                        \"urls\": [\r\n"
					+ "                            {\r\n"
					+ "                                \"display_url\": \"luigimarattin.it\",\r\n"
					+ "                                \"indices\": [\r\n"
					+ "                                    116,\r\n"
					+ "                                    139\r\n"
					+ "                                ],\r\n"
					+ "                                \"expanded_url\": \"http://www.luigimarattin.it\",\r\n"
					+ "                                \"url\": \"https://t.co/z5RPHrC0h2\"\r\n"
					+ "                            }\r\n"
					+ "                        ]\r\n"
					+ "                    },\r\n"
					+ "                    \"url\": {\r\n"
					+ "                        \"urls\": [\r\n"
					+ "                            {\r\n"
					+ "                                \"display_url\": \"luigimarattin.it\",\r\n"
					+ "                                \"indices\": [\r\n"
					+ "                                    0,\r\n"
					+ "                                    23\r\n"
					+ "                                ],\r\n"
					+ "                                \"expanded_url\": \"http://www.luigimarattin.it\",\r\n"
					+ "                                \"url\": \"https://t.co/z5RPHrC0h2\"\r\n"
					+ "                            }\r\n"
					+ "                        ]\r\n"
					+ "                    }\r\n"
					+ "                },\r\n"
					+ "                \"statuses_count\": 12378,\r\n"
					+ "                \"follow_request_sent\": null,\r\n"
					+ "                \"followers_count\": 68872,\r\n"
					+ "                \"profile_use_background_image\": true,\r\n"
					+ "                \"default_profile\": true,\r\n"
					+ "                \"following\": null,\r\n"
					+ "                \"name\": \"Luigi Marattin\",\r\n"
					+ "                \"location\": \"\",\r\n"
					+ "                \"profile_sidebar_fill_color\": \"DDEEF6\",\r\n"
					+ "                \"notifications\": null\r\n"
					+ "            }\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "            \"metadata\": {\r\n"
					+ "                \"result_type\": \"popular\",\r\n"
					+ "                \"iso_language_code\": \"it\"\r\n"
					+ "            },\r\n"
					+ "            \"in_reply_to_status_id_str\": null,\r\n"
					+ "            \"in_reply_to_status_id\": null,\r\n"
					+ "            \"possibly_sensitive\": false,\r\n"
					+ "            \"coordinates\": null,\r\n"
					+ "            \"created_at\": \"Mon Jan 10 21:33:51 +0000 2022\",\r\n"
					+ "            \"truncated\": false,\r\n"
					+ "            \"in_reply_to_user_id_str\": null,\r\n"
					+ "            \"source\": \"<a href=\\\"http://www.gazzetta.it\\\" rel=\\\"nofollow\\\">TweetFromMethode</a>\",\r\n"
					+ "            \"retweet_count\": 172,\r\n"
					+ "            \"retweeted\": false,\r\n"
					+ "            \"geo\": null,\r\n"
					+ "            \"in_reply_to_screen_name\": null,\r\n"
					+ "            \"is_quote_status\": false,\r\n"
					+ "            \"id_str\": \"1480654141491982342\",\r\n"
					+ "            \"in_reply_to_user_id\": null,\r\n"
					+ "            \"favorite_count\": 1058,\r\n"
					+ "            \"id\": 1480654141491982342,\r\n"
					+ "            \"text\": \"Inter - Brozovic, c'è l'accordo. Marcelo rinnova fino al 2026. Annuncio dopo la Supercoppa https://t.co/ad387zkSEn\",\r\n"
					+ "            \"place\": null,\r\n"
					+ "            \"contributors\": null,\r\n"
					+ "            \"lang\": \"it\",\r\n"
					+ "            \"user\": {\r\n"
					+ "                \"utc_offset\": null,\r\n"
					+ "                \"friends_count\": 291,\r\n"
					+ "                \"profile_image_url_https\": \"https://pbs.twimg.com/profile_images/1007020730767245313/P6VR9MwA_normal.jpg\",\r\n"
					+ "                \"listed_count\": 6785,\r\n"
					+ "                \"profile_background_image_url\": \"http://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"default_profile_image\": false,\r\n"
					+ "                \"favourites_count\": 6184,\r\n"
					+ "                \"description\": \"La pagina ufficiale de La Gazzetta dello Sport, il quotidiano sportivo più diffuso in Italia.\",\r\n"
					+ "                \"created_at\": \"Tue Oct 27 18:15:06 +0000 2009\",\r\n"
					+ "                \"is_translator\": false,\r\n"
					+ "                \"withheld_in_countries\": [],\r\n"
					+ "                \"profile_background_image_url_https\": \"https://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"protected\": false,\r\n"
					+ "                \"screen_name\": \"Gazzetta_it\",\r\n"
					+ "                \"id_str\": \"85626417\",\r\n"
					+ "                \"profile_link_color\": \"0084B4\",\r\n"
					+ "                \"is_translation_enabled\": false,\r\n"
					+ "                \"translator_type\": \"none\",\r\n"
					+ "                \"id\": 85626417,\r\n"
					+ "                \"geo_enabled\": true,\r\n"
					+ "                \"profile_background_color\": \"C0DEED\",\r\n"
					+ "                \"lang\": null,\r\n"
					+ "                \"has_extended_profile\": false,\r\n"
					+ "                \"profile_sidebar_border_color\": \"FFFFFF\",\r\n"
					+ "                \"profile_text_color\": \"333333\",\r\n"
					+ "                \"verified\": true,\r\n"
					+ "                \"profile_image_url\": \"http://pbs.twimg.com/profile_images/1007020730767245313/P6VR9MwA_normal.jpg\",\r\n"
					+ "                \"time_zone\": null,\r\n"
					+ "                \"url\": \"https://t.co/MtnMDvYQ3I\",\r\n"
					+ "                \"contributors_enabled\": false,\r\n"
					+ "                \"profile_background_tile\": false,\r\n"
					+ "                \"profile_banner_url\": \"https://pbs.twimg.com/profile_banners/85626417/1641399775\",\r\n"
					+ "                \"entities\": {\r\n"
					+ "                    \"description\": {\r\n"
					+ "                        \"urls\": []\r\n"
					+ "                    },\r\n"
					+ "                    \"url\": {\r\n"
					+ "                        \"urls\": [\r\n"
					+ "                            {\r\n"
					+ "                                \"display_url\": \"gazzetta.it\",\r\n"
					+ "                                \"indices\": [\r\n"
					+ "                                    0,\r\n"
					+ "                                    23\r\n"
					+ "                                ],\r\n"
					+ "                                \"expanded_url\": \"http://www.gazzetta.it\",\r\n"
					+ "                                \"url\": \"https://t.co/MtnMDvYQ3I\"\r\n"
					+ "                            }\r\n"
					+ "                        ]\r\n"
					+ "                    }\r\n"
					+ "                },\r\n"
					+ "                \"statuses_count\": 350410,\r\n"
					+ "                \"follow_request_sent\": null,\r\n"
					+ "                \"followers_count\": 1833741,\r\n"
					+ "                \"profile_use_background_image\": true,\r\n"
					+ "                \"default_profile\": false,\r\n"
					+ "                \"following\": null,\r\n"
					+ "                \"name\": \"La Gazzetta dello Sport\",\r\n"
					+ "                \"location\": \"Italy\",\r\n"
					+ "                \"profile_sidebar_fill_color\": \"DDEEF6\",\r\n"
					+ "                \"notifications\": null\r\n"
					+ "            },\r\n"
					+ "            \"favorited\": false\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "            \"metadata\": {\r\n"
					+ "                \"result_type\": \"popular\",\r\n"
					+ "                \"iso_language_code\": \"en\"\r\n"
					+ "            },\r\n"
					+ "            \"in_reply_to_status_id_str\": null,\r\n"
					+ "            \"in_reply_to_status_id\": null,\r\n"
					+ "            \"possibly_sensitive\": false,\r\n"
					+ "            \"coordinates\": null,\r\n"
					+ "            \"created_at\": \"Mon Jan 10 21:41:35 +0000 2022\",\r\n"
					+ "            \"truncated\": true,\r\n"
					+ "            \"in_reply_to_user_id_str\": null,\r\n"
					+ "            \"source\": \"<a href=\\\"http://twitter.com/download/android\\\" rel=\\\"nofollow\\\">Twitter for Android</a>\",\r\n"
					+ "            \"retweet_count\": 94,\r\n"
					+ "            \"retweeted\": false,\r\n"
					+ "            \"geo\": null,\r\n"
					+ "            \"in_reply_to_screen_name\": null,\r\n"
					+ "            \"is_quote_status\": false,\r\n"
					+ "            \"id_str\": \"1480656088194338819\",\r\n"
					+ "            \"in_reply_to_user_id\": null,\r\n"
					+ "            \"favorite_count\": 1002,\r\n"
					+ "            \"id\": 1480656088194338819,\r\n"
					+ "            \"text\": \"OFFICIAL: Ghanaian youngster @AwuaAhmed signs two and half year deal with Parma Calcio.\\n\\nMy boy from Yamfo is now a… https://t.co/LfPcQSyn75\",\r\n"
					+ "            \"place\": null,\r\n"
					+ "            \"contributors\": null,\r\n"
					+ "            \"lang\": \"en\",\r\n"
					+ "            \"user\": {\r\n"
					+ "                \"utc_offset\": null,\r\n"
					+ "                \"friends_count\": 408,\r\n"
					+ "                \"profile_image_url_https\": \"https://pbs.twimg.com/profile_images/1477867655180824576/AUpcpwoS_normal.jpg\",\r\n"
					+ "                \"listed_count\": 131,\r\n"
					+ "                \"profile_background_image_url\": \"http://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"default_profile_image\": false,\r\n"
					+ "                \"favourites_count\": 2447,\r\n"
					+ "                \"description\": \"Award-winning Sports Journalist \\n\\n| African Football |\",\r\n"
					+ "                \"created_at\": \"Sat Oct 24 20:25:14 +0000 2015\",\r\n"
					+ "                \"is_translator\": false,\r\n"
					+ "                \"withheld_in_countries\": [],\r\n"
					+ "                \"profile_background_image_url_https\": \"https://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"protected\": false,\r\n"
					+ "                \"screen_name\": \"SaddickAdams\",\r\n"
					+ "                \"id_str\": \"4033989881\",\r\n"
					+ "                \"profile_link_color\": \"1DA1F2\",\r\n"
					+ "                \"is_translation_enabled\": false,\r\n"
					+ "                \"translator_type\": \"none\",\r\n"
					+ "                \"id\": 4033989881,\r\n"
					+ "                \"geo_enabled\": true,\r\n"
					+ "                \"profile_background_color\": \"C0DEED\",\r\n"
					+ "                \"lang\": null,\r\n"
					+ "                \"has_extended_profile\": true,\r\n"
					+ "                \"profile_sidebar_border_color\": \"C0DEED\",\r\n"
					+ "                \"profile_text_color\": \"333333\",\r\n"
					+ "                \"verified\": true,\r\n"
					+ "                \"profile_image_url\": \"http://pbs.twimg.com/profile_images/1477867655180824576/AUpcpwoS_normal.jpg\",\r\n"
					+ "                \"time_zone\": null,\r\n"
					+ "                \"url\": null,\r\n"
					+ "                \"contributors_enabled\": false,\r\n"
					+ "                \"profile_background_tile\": false,\r\n"
					+ "                \"profile_banner_url\": \"https://pbs.twimg.com/profile_banners/4033989881/1619515881\",\r\n"
					+ "                \"entities\": {\r\n"
					+ "                    \"description\": {\r\n"
					+ "                        \"urls\": []\r\n"
					+ "                    }\r\n"
					+ "                },\r\n"
					+ "                \"statuses_count\": 33306,\r\n"
					+ "                \"follow_request_sent\": null,\r\n"
					+ "                \"followers_count\": 371072,\r\n"
					+ "                \"profile_use_background_image\": true,\r\n"
					+ "                \"default_profile\": true,\r\n"
					+ "                \"following\": null,\r\n"
					+ "                \"name\": \"Saddick Adams\",\r\n"
					+ "                \"location\": \"Accra, Ghana\",\r\n"
					+ "                \"profile_sidebar_fill_color\": \"DDEEF6\",\r\n"
					+ "                \"notifications\": null\r\n"
					+ "            },\r\n"
					+ "            \"favorited\": false\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "            \"metadata\": {\r\n"
					+ "                \"result_type\": \"popular\",\r\n"
					+ "                \"iso_language_code\": \"it\"\r\n"
					+ "            },\r\n"
					+ "            \"in_reply_to_status_id_str\": null,\r\n"
					+ "            \"in_reply_to_status_id\": null,\r\n"
					+ "            \"coordinates\": null,\r\n"
					+ "            \"created_at\": \"Sun Jan 09 19:14:13 +0000 2022\",\r\n"
					+ "            \"truncated\": false,\r\n"
					+ "            \"in_reply_to_user_id_str\": null,\r\n"
					+ "            \"source\": \"<a href=\\\"https://mobile.twitter.com\\\" rel=\\\"nofollow\\\">Twitter Web App</a>\",\r\n"
					+ "            \"retweet_count\": 43,\r\n"
					+ "            \"retweeted\": false,\r\n"
					+ "            \"geo\": null,\r\n"
					+ "            \"in_reply_to_screen_name\": null,\r\n"
					+ "            \"is_quote_status\": false,\r\n"
					+ "            \"id_str\": \"1480256614787690498\",\r\n"
					+ "            \"in_reply_to_user_id\": null,\r\n"
					+ "            \"favorite_count\": 782,\r\n"
					+ "            \"id\": 1480256614787690498,\r\n"
					+ "            \"text\": \"81' | Calcio di rigore per la Roma ed espulso @mdeligt_04 \\n😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱\",\r\n"
					+ "            \"place\": null,\r\n"
					+ "            \"contributors\": null,\r\n"
					+ "            \"lang\": \"it\",\r\n"
					+ "            \"user\": {\r\n"
					+ "                \"utc_offset\": null,\r\n"
					+ "                \"friends_count\": 65,\r\n"
					+ "                \"profile_image_url_https\": \"https://pbs.twimg.com/profile_images/1464673446953168900/eZNug-9R_normal.jpg\",\r\n"
					+ "                \"listed_count\": 8900,\r\n"
					+ "                \"profile_background_image_url\": \"http://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"default_profile_image\": false,\r\n"
					+ "                \"favourites_count\": 3086,\r\n"
					+ "                \"description\": \"Profilo Twitter ufficiale della Juventus. 🇬🇧@juventusfcen 🇪🇸@juventusfces, 🇵🇹🇧🇷@juventusfcpt, العربية @juventusfcar, @juventusfcyouth & @juventusfcwomen\",\r\n"
					+ "                \"created_at\": \"Thu Feb 17 11:34:21 +0000 2011\",\r\n"
					+ "                \"is_translator\": false,\r\n"
					+ "                \"withheld_in_countries\": [],\r\n"
					+ "                \"profile_background_image_url_https\": \"https://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"protected\": false,\r\n"
					+ "                \"screen_name\": \"juventusfc\",\r\n"
					+ "                \"id_str\": \"253508662\",\r\n"
					+ "                \"profile_link_color\": \"D1A400\",\r\n"
					+ "                \"is_translation_enabled\": true,\r\n"
					+ "                \"translator_type\": \"regular\",\r\n"
					+ "                \"id\": 253508662,\r\n"
					+ "                \"geo_enabled\": true,\r\n"
					+ "                \"profile_background_color\": \"000000\",\r\n"
					+ "                \"lang\": null,\r\n"
					+ "                \"has_extended_profile\": true,\r\n"
					+ "                \"profile_sidebar_border_color\": \"FFFFFF\",\r\n"
					+ "                \"profile_text_color\": \"333333\",\r\n"
					+ "                \"verified\": true,\r\n"
					+ "                \"profile_image_url\": \"http://pbs.twimg.com/profile_images/1464673446953168900/eZNug-9R_normal.jpg\",\r\n"
					+ "                \"time_zone\": null,\r\n"
					+ "                \"url\": \"https://t.co/jTew2lFM3o\",\r\n"
					+ "                \"contributors_enabled\": false,\r\n"
					+ "                \"profile_background_tile\": false,\r\n"
					+ "                \"profile_banner_url\": \"https://pbs.twimg.com/profile_banners/253508662/1641828493\",\r\n"
					+ "                \"entities\": {\r\n"
					+ "                    \"description\": {\r\n"
					+ "                        \"urls\": []\r\n"
					+ "                    },\r\n"
					+ "                    \"url\": {\r\n"
					+ "                        \"urls\": [\r\n"
					+ "                            {\r\n"
					+ "                                \"display_url\": \"juventus.com\",\r\n"
					+ "                                \"indices\": [\r\n"
					+ "                                    0,\r\n"
					+ "                                    23\r\n"
					+ "                                ],\r\n"
					+ "                                \"expanded_url\": \"http://www.juventus.com\",\r\n"
					+ "                                \"url\": \"https://t.co/jTew2lFM3o\"\r\n"
					+ "                            }\r\n"
					+ "                        ]\r\n"
					+ "                    }\r\n"
					+ "                },\r\n"
					+ "                \"statuses_count\": 100236,\r\n"
					+ "                \"follow_request_sent\": null,\r\n"
					+ "                \"followers_count\": 9617190,\r\n"
					+ "                \"profile_use_background_image\": true,\r\n"
					+ "                \"default_profile\": false,\r\n"
					+ "                \"following\": null,\r\n"
					+ "                \"name\": \"JuventusFC\",\r\n"
					+ "                \"location\": \"Allianz Stadium\",\r\n"
					+ "                \"profile_sidebar_fill_color\": \"F3F3EB\",\r\n"
					+ "                \"notifications\": null\r\n"
					+ "            },\r\n"
					+ "            \"favorited\": false\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "            \"metadata\": {\r\n"
					+ "                \"result_type\": \"popular\",\r\n"
					+ "                \"iso_language_code\": \"es\"\r\n"
					+ "            },\r\n"
					+ "            \"in_reply_to_status_id_str\": null,\r\n"
					+ "            \"in_reply_to_status_id\": null,\r\n"
					+ "            \"possibly_sensitive\": false,\r\n"
					+ "            \"coordinates\": null,\r\n"
					+ "            \"created_at\": \"Sun Jan 09 22:35:14 +0000 2022\",\r\n"
					+ "            \"truncated\": false,\r\n"
					+ "            \"in_reply_to_user_id_str\": null,\r\n"
					+ "            \"source\": \"<a href=\\\"https://about.twitter.com/products/tweetdeck\\\" rel=\\\"nofollow\\\">TweetDeck</a>\",\r\n"
					+ "            \"retweet_count\": 21,\r\n"
					+ "            \"retweeted\": false,\r\n"
					+ "            \"geo\": null,\r\n"
					+ "            \"in_reply_to_screen_name\": null,\r\n"
					+ "            \"is_quote_status\": false,\r\n"
					+ "            \"id_str\": \"1480307203399684105\",\r\n"
					+ "            \"in_reply_to_user_id\": null,\r\n"
					+ "            \"favorite_count\": 445,\r\n"
					+ "            \"id\": 1480307203399684105,\r\n"
					+ "            \"text\": \"Hoy se marcaron 32 goles en 8 partidos de la #SerieAxESPN. ¡Viva el Calcio! https://t.co/FE9ukk2X4P\",\r\n"
					+ "            \"place\": null,\r\n"
					+ "            \"contributors\": null,\r\n"
					+ "            \"lang\": \"es\",\r\n"
					+ "            \"user\": {\r\n"
					+ "                \"utc_offset\": null,\r\n"
					+ "                \"friends_count\": 20,\r\n"
					+ "                \"profile_image_url_https\": \"https://pbs.twimg.com/profile_images/1333080675143004160/c_lzvUJw_normal.png\",\r\n"
					+ "                \"listed_count\": 2968,\r\n"
					+ "                \"profile_background_image_url\": \"http://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"default_profile_image\": false,\r\n"
					+ "                \"favourites_count\": 89,\r\n"
					+ "                \"description\": \"Noticiero del deporte mundial. Repaso de toda la actualidad con compactos, entrevistas, destacados. Un estilo de vida, todos los días, en ESPN.\",\r\n"
					+ "                \"created_at\": \"Wed Mar 14 17:00:18 +0000 2012\",\r\n"
					+ "                \"is_translator\": false,\r\n"
					+ "                \"withheld_in_countries\": [],\r\n"
					+ "                \"profile_background_image_url_https\": \"https://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"protected\": false,\r\n"
					+ "                \"screen_name\": \"SC_ESPN\",\r\n"
					+ "                \"id_str\": \"524531680\",\r\n"
					+ "                \"profile_link_color\": \"0084B4\",\r\n"
					+ "                \"is_translation_enabled\": false,\r\n"
					+ "                \"translator_type\": \"none\",\r\n"
					+ "                \"id\": 524531680,\r\n"
					+ "                \"geo_enabled\": false,\r\n"
					+ "                \"profile_background_color\": \"C0DEED\",\r\n"
					+ "                \"lang\": null,\r\n"
					+ "                \"has_extended_profile\": false,\r\n"
					+ "                \"profile_sidebar_border_color\": \"FFFFFF\",\r\n"
					+ "                \"profile_text_color\": \"333333\",\r\n"
					+ "                \"verified\": true,\r\n"
					+ "                \"profile_image_url\": \"http://pbs.twimg.com/profile_images/1333080675143004160/c_lzvUJw_normal.png\",\r\n"
					+ "                \"time_zone\": null,\r\n"
					+ "                \"url\": \"https://t.co/ysbzEklsPD\",\r\n"
					+ "                \"contributors_enabled\": false,\r\n"
					+ "                \"profile_background_tile\": false,\r\n"
					+ "                \"profile_banner_url\": \"https://pbs.twimg.com/profile_banners/524531680/1607572320\",\r\n"
					+ "                \"entities\": {\r\n"
					+ "                    \"description\": {\r\n"
					+ "                        \"urls\": []\r\n"
					+ "                    },\r\n"
					+ "                    \"url\": {\r\n"
					+ "                        \"urls\": [\r\n"
					+ "                            {\r\n"
					+ "                                \"display_url\": \"terminosdeuso.espn-la.com\",\r\n"
					+ "                                \"indices\": [\r\n"
					+ "                                    0,\r\n"
					+ "                                    23\r\n"
					+ "                                ],\r\n"
					+ "                                \"expanded_url\": \"http://terminosdeuso.espn-la.com\",\r\n"
					+ "                                \"url\": \"https://t.co/ysbzEklsPD\"\r\n"
					+ "                            }\r\n"
					+ "                        ]\r\n"
					+ "                    }\r\n"
					+ "                },\r\n"
					+ "                \"statuses_count\": 826079,\r\n"
					+ "                \"follow_request_sent\": null,\r\n"
					+ "                \"followers_count\": 2332671,\r\n"
					+ "                \"profile_use_background_image\": true,\r\n"
					+ "                \"default_profile\": false,\r\n"
					+ "                \"following\": null,\r\n"
					+ "                \"name\": \"SportsCenter\",\r\n"
					+ "                \"location\": \"\",\r\n"
					+ "                \"profile_sidebar_fill_color\": \"DDEEF6\",\r\n"
					+ "                \"notifications\": null\r\n"
					+ "            },\r\n"
					+ "            \"favorited\": false\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "            \"metadata\": {\r\n"
					+ "                \"result_type\": \"popular\",\r\n"
					+ "                \"iso_language_code\": \"it\"\r\n"
					+ "            },\r\n"
					+ "            \"in_reply_to_status_id_str\": null,\r\n"
					+ "            \"in_reply_to_status_id\": null,\r\n"
					+ "            \"possibly_sensitive\": false,\r\n"
					+ "            \"coordinates\": null,\r\n"
					+ "            \"created_at\": \"Sun Jan 09 17:31:59 +0000 2022\",\r\n"
					+ "            \"truncated\": false,\r\n"
					+ "            \"in_reply_to_user_id_str\": null,\r\n"
					+ "            \"source\": \"<a href=\\\"https://mobile.twitter.com\\\" rel=\\\"nofollow\\\">Twitter Web App</a>\",\r\n"
					+ "            \"retweet_count\": 19,\r\n"
					+ "            \"retweeted\": false,\r\n"
					+ "            \"geo\": null,\r\n"
					+ "            \"in_reply_to_screen_name\": null,\r\n"
					+ "            \"is_quote_status\": false,\r\n"
					+ "            \"id_str\": \"1480230886213828616\",\r\n"
					+ "            \"in_reply_to_user_id\": null,\r\n"
					+ "            \"favorite_count\": 146,\r\n"
					+ "            \"id\": 1480230886213828616,\r\n"
					+ "            \"text\": \"CALCIO D'INIZIO! 🙌\\n\\nDAJE ROMA DAJEEEE! 🟡🔴\\n\\n#RomaJuve https://t.co/MnpcKv53Br\",\r\n"
					+ "            \"place\": null,\r\n"
					+ "            \"contributors\": null,\r\n"
					+ "            \"lang\": \"it\",\r\n"
					+ "            \"user\": {\r\n"
					+ "                \"utc_offset\": null,\r\n"
					+ "                \"friends_count\": 1297,\r\n"
					+ "                \"profile_image_url_https\": \"https://pbs.twimg.com/profile_images/1369060900385263619/LnIBVo2Y_normal.png\",\r\n"
					+ "                \"listed_count\": 4645,\r\n"
					+ "                \"profile_background_image_url\": \"http://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"default_profile_image\": false,\r\n"
					+ "                \"favourites_count\": 11801,\r\n"
					+ "                \"description\": \"Profilo Twitter ufficiale dell'AS Roma. Altre lingue: @ASRomaEN @ASRomaArabic Copyright: https://t.co/iYxMaVKNEe…\",\r\n"
					+ "                \"created_at\": \"Mon Sep 26 21:36:17 +0000 2011\",\r\n"
					+ "                \"is_translator\": false,\r\n"
					+ "                \"withheld_in_countries\": [],\r\n"
					+ "                \"profile_background_image_url_https\": \"https://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"protected\": false,\r\n"
					+ "                \"screen_name\": \"OfficialASRoma\",\r\n"
					+ "                \"id_str\": \"380570951\",\r\n"
					+ "                \"profile_link_color\": \"FBBA00\",\r\n"
					+ "                \"is_translation_enabled\": false,\r\n"
					+ "                \"translator_type\": \"regular\",\r\n"
					+ "                \"id\": 380570951,\r\n"
					+ "                \"geo_enabled\": true,\r\n"
					+ "                \"profile_background_color\": \"080003\",\r\n"
					+ "                \"lang\": null,\r\n"
					+ "                \"has_extended_profile\": false,\r\n"
					+ "                \"profile_sidebar_border_color\": \"FFFFFF\",\r\n"
					+ "                \"profile_text_color\": \"050505\",\r\n"
					+ "                \"verified\": true,\r\n"
					+ "                \"profile_image_url\": \"http://pbs.twimg.com/profile_images/1369060900385263619/LnIBVo2Y_normal.png\",\r\n"
					+ "                \"time_zone\": null,\r\n"
					+ "                \"url\": \"https://t.co/l6YDCGa2Yl\",\r\n"
					+ "                \"contributors_enabled\": false,\r\n"
					+ "                \"profile_background_tile\": true,\r\n"
					+ "                \"profile_banner_url\": \"https://pbs.twimg.com/profile_banners/380570951/1639850152\",\r\n"
					+ "                \"entities\": {\r\n"
					+ "                    \"description\": {\r\n"
					+ "                        \"urls\": [\r\n"
					+ "                            {\r\n"
					+ "                                \"display_url\": \"asroma.com/it/condizioni-\",\r\n"
					+ "                                \"indices\": [\r\n"
					+ "                                    89,\r\n"
					+ "                                    112\r\n"
					+ "                                ],\r\n"
					+ "                                \"expanded_url\": \"http://asroma.com/it/condizioni-\",\r\n"
					+ "                                \"url\": \"https://t.co/iYxMaVKNEe\"\r\n"
					+ "                            }\r\n"
					+ "                        ]\r\n"
					+ "                    },\r\n"
					+ "                    \"url\": {\r\n"
					+ "                        \"urls\": [\r\n"
					+ "                            {\r\n"
					+ "                                \"display_url\": \"asroma.com/it\",\r\n"
					+ "                                \"indices\": [\r\n"
					+ "                                    0,\r\n"
					+ "                                    23\r\n"
					+ "                                ],\r\n"
					+ "                                \"expanded_url\": \"http://www.asroma.com/it\",\r\n"
					+ "                                \"url\": \"https://t.co/l6YDCGa2Yl\"\r\n"
					+ "                            }\r\n"
					+ "                        ]\r\n"
					+ "                    }\r\n"
					+ "                },\r\n"
					+ "                \"statuses_count\": 79963,\r\n"
					+ "                \"follow_request_sent\": null,\r\n"
					+ "                \"followers_count\": 2042984,\r\n"
					+ "                \"profile_use_background_image\": true,\r\n"
					+ "                \"default_profile\": false,\r\n"
					+ "                \"following\": null,\r\n"
					+ "                \"name\": \"AS Roma\",\r\n"
					+ "                \"location\": \"Roma | Rome\",\r\n"
					+ "                \"profile_sidebar_fill_color\": \"F7A043\",\r\n"
					+ "                \"notifications\": null\r\n"
					+ "            },\r\n"
					+ "            \"favorited\": false\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "            \"metadata\": {\r\n"
					+ "                \"result_type\": \"popular\",\r\n"
					+ "                \"iso_language_code\": \"it\"\r\n"
					+ "            },\r\n"
					+ "            \"in_reply_to_status_id_str\": null,\r\n"
					+ "            \"in_reply_to_status_id\": null,\r\n"
					+ "            \"possibly_sensitive\": false,\r\n"
					+ "            \"coordinates\": null,\r\n"
					+ "            \"created_at\": \"Mon Jan 10 12:30:27 +0000 2022\",\r\n"
					+ "            \"truncated\": true,\r\n"
					+ "            \"in_reply_to_user_id_str\": null,\r\n"
					+ "            \"source\": \"<a href=\\\"http://twitter.com/download/iphone\\\" rel=\\\"nofollow\\\">Twitter for iPhone</a>\",\r\n"
					+ "            \"retweet_count\": 31,\r\n"
					+ "            \"retweeted\": false,\r\n"
					+ "            \"geo\": null,\r\n"
					+ "            \"in_reply_to_screen_name\": null,\r\n"
					+ "            \"is_quote_status\": false,\r\n"
					+ "            \"id_str\": \"1480517392887394304\",\r\n"
					+ "            \"in_reply_to_user_id\": null,\r\n"
					+ "            \"favorite_count\": 578,\r\n"
					+ "            \"id\": 1480517392887394304,\r\n"
					+ "            \"text\": \"Esistono momenti dove si va oltre le rivalità sportive, specialmente di fronte ad un brutto infortunio. Ancora una… https://t.co/OXLdVlSwhK\",\r\n"
					+ "            \"place\": null,\r\n"
					+ "            \"contributors\": null,\r\n"
					+ "            \"lang\": \"it\",\r\n"
					+ "            \"user\": {\r\n"
					+ "                \"utc_offset\": null,\r\n"
					+ "                \"friends_count\": 529,\r\n"
					+ "                \"profile_image_url_https\": \"https://pbs.twimg.com/profile_images/1480215720696987655/BuORgLdh_normal.jpg\",\r\n"
					+ "                \"listed_count\": 309,\r\n"
					+ "                \"profile_background_image_url\": \"http://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"default_profile_image\": false,\r\n"
					+ "                \"favourites_count\": 7103,\r\n"
					+ "                \"description\": \"Lo spogliatoio più grande d’Italia.\",\r\n"
					+ "                \"created_at\": \"Tue Mar 05 09:39:14 +0000 2013\",\r\n"
					+ "                \"is_translator\": false,\r\n"
					+ "                \"withheld_in_countries\": [],\r\n"
					+ "                \"profile_background_image_url_https\": \"https://abs.twimg.com/images/themes/theme1/bg.png\",\r\n"
					+ "                \"protected\": false,\r\n"
					+ "                \"screen_name\": \"CB_Ignoranza\",\r\n"
					+ "                \"id_str\": \"1243312284\",\r\n"
					+ "                \"profile_link_color\": \"4A913C\",\r\n"
					+ "                \"is_translation_enabled\": false,\r\n"
					+ "                \"translator_type\": \"none\",\r\n"
					+ "                \"id\": 1243312284,\r\n"
					+ "                \"geo_enabled\": true,\r\n"
					+ "                \"profile_background_color\": \"C0DEED\",\r\n"
					+ "                \"lang\": null,\r\n"
					+ "                \"has_extended_profile\": true,\r\n"
					+ "                \"profile_sidebar_border_color\": \"C0DEED\",\r\n"
					+ "                \"profile_text_color\": \"333333\",\r\n"
					+ "                \"verified\": true,\r\n"
					+ "                \"profile_image_url\": \"http://pbs.twimg.com/profile_images/1480215720696987655/BuORgLdh_normal.jpg\",\r\n"
					+ "                \"time_zone\": null,\r\n"
					+ "                \"url\": \"https://t.co/K5thICPMgQ\",\r\n"
					+ "                \"contributors_enabled\": false,\r\n"
					+ "                \"profile_background_tile\": false,\r\n"
					+ "                \"profile_banner_url\": \"https://pbs.twimg.com/profile_banners/1243312284/1583428496\",\r\n"
					+ "                \"entities\": {\r\n"
					+ "                    \"description\": {\r\n"
					+ "                        \"urls\": []\r\n"
					+ "                    },\r\n"
					+ "                    \"url\": {\r\n"
					+ "                        \"urls\": [\r\n"
					+ "                            {\r\n"
					+ "                                \"display_url\": \"calciatoribrutti.com\",\r\n"
					+ "                                \"indices\": [\r\n"
					+ "                                    0,\r\n"
					+ "                                    23\r\n"
					+ "                                ],\r\n"
					+ "                                \"expanded_url\": \"http://www.calciatoribrutti.com\",\r\n"
					+ "                                \"url\": \"https://t.co/K5thICPMgQ\"\r\n"
					+ "                            }\r\n"
					+ "                        ]\r\n"
					+ "                    }\r\n"
					+ "                },\r\n"
					+ "                \"statuses_count\": 10465,\r\n"
					+ "                \"follow_request_sent\": null,\r\n"
					+ "                \"followers_count\": 250731,\r\n"
					+ "                \"profile_use_background_image\": true,\r\n"
					+ "                \"default_profile\": false,\r\n"
					+ "                \"following\": null,\r\n"
					+ "                \"name\": \"CALCIATORI BRUTTI\",\r\n"
					+ "                \"location\": \"info@calciatoribrutti.com\",\r\n"
					+ "                \"profile_sidebar_fill_color\": \"DDEEF6\",\r\n"
					+ "                \"notifications\": null\r\n"
					+ "            },\r\n"
					+ "            \"favorited\": false\r\n"
					+ "        }\r\n"
					+ "    ],\r\n"
					+ "    \"search_metadata\": {\r\n"
					+ "        \"max_id_str\": \"0\",\r\n"
					+ "        \"next_results\": \"?max_id=1480172939353985027&q=calcio&lang=&count=10&result_type=popular\",\r\n"
					+ "        \"since_id_str\": \"0\",\r\n"
					+ "        \"query\": \"calcio\",\r\n"
					+ "        \"count\": 10,\r\n"
					+ "        \"max_id\": 0,\r\n"
					+ "        \"since_id\": 0,\r\n"
					+ "        \"completed_in\": 0.038\r\n"
					+ "    }\r\n"
					+ "}");	 //parse JSON Object from contenuto
			System.out.println( "OK" );
			saveOnFile(jasonObj);
			
			return jasonObj;
			
		} catch ( /*IOException|*/ ParseException e) {
			e.printStackTrace();
		} catch ( Exception e) {
			e.printStackTrace();
		}
	
		return null;
	}
	
	public void saveOnFile(JSONObject jasonObj)
	{
        try (FileWriter file = new FileWriter("fileD'appoggio.txt")) {
            file.write(jasonObj.toJSONString());
        } catch (IOException e) {
            e.printStackTrace();
        }
	}
	
}
